# Generated by Django 4.1.5 on 2023-01-31 08:34

from django.db import migrations, models
import django.db.models.deletion
import network_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_app', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(height_field=100, upload_to=network_app.models.user_directory_path, width_field=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='create data')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='update data')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='accounts_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='create data')),
                ('commentator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts_app.profile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='network_app.post')),
            ],
        ),
    ]
