# Generated by Django 4.1.5 on 2023-01-31 09:33

from django.db import migrations, models
import network_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0002_alter_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(upload_to=network_app.models.user_directory_path),
        ),
    ]
