# Generated by Django 4.1.5 on 2023-02-03 05:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0004_rating_post_rates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rates',
        ),
        migrations.AlterField(
            model_name='rating',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='network_app.post'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
