# Generated by Django 4.1.5 on 2023-02-03 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0006_commentlikes_rating_valid_rate_rating_rating_once_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='valid_rate',
        ),
        migrations.RemoveConstraint(
            model_name='rating',
            name='rating_once',
        ),
    ]
